export const SELLER_SIGNUP_REQUEST1 = 'SELLER_SIGNUP_REQUEST1';
export const SELLER_SIGNUP_SUCCESS1 = 'SELLER_SIGNUP_SUCCESS1';
export const SELLER_SIGNUP_FAIL1 = 'SELLER_SIGNUP_FAIL1';
export const SELLER_DETAILS_RESET1 = 'SELLER_DETAILS_RESET1';