export const VERIFICATION_CREATE_REQUEST = 'VERIFICATION_CREATE_REQUEST';
export const VERIFICATION_CREATE_SUCCESS = 'VERIFICATION_CREATE_SUCCESS';
export const VERIFICATION_CREATE_FAIL = 'VERIFICATION_CREATE_FAIL';

export const VERIFICATION_GET_REQUEST = 'VERIFICATION_GET_REQUEST';
export const VERIFICATION_GET_SUCCESS = 'VERIFICATION_GET_SUCCESS';
export const VERIFICATION_GET_FAIL = 'VERIFICATION_GET_FAIL';